//
//  DataModel.swift
//  ModelParser
//
//  Created by Peter Livesey on 1/6/17.
//  Copyright © 2017 Peter Livesey. All rights reserved.
//

import Foundation

/**
 This protocol is implemented by all the data models generated by SwiftGen.
 It allows you to convert a model to `[String: Any]` and `[String: Any]` to a model.
 */
public protocol DataModel: DataConvertible {
    /**
     Converts a `DataModel` to `[String: Any]` representation.
     */
    func data() -> [String: Any]
}

extension DataModel {
    /**
     This overrides the default method which returns `Any` to return the method that returns `[String: Any]`
     */
    public func dataRepresentation() -> Any {
        return data()
    }
}
